### ISSUE TITLE
Shutdown hook

### ISSUE THREAD

**Issue by DimTheo** [anchan828/nest-redlock#492]
https://github.com/anchan828/nest-redlock/blob/571d91242aea65514d45a05884c162f87987f8b4/packages/redlock/src/redlock.module.ts#L16C1-L34C3

`OnModuleDestroy` kills the redis clients early, which means any locked resources still running/being processed (like queue messages) will throw `The operation was unable to achieve a quorum during its retry window.` error. 

Changing the code above to use `OnApplicationShutdown` hook would prevent these kind of issues.

**Comment by anchan828** [comment]
Hi @DimTheo, Thanks for the suggestion. Your suggestion makes sense.
This was changed by [this PR](https://github.com/anchan828/nest-redlock/pull/493) and a new version was released. Please try it out.

https://www.npmjs.com/package/@anchan828/nest-redlock/v/0.2.0

**Comment by anchan828** [comment]
If you have any problems, please create another issue.
