### ISSUE TITLE
The operation was unable to achieve a quorum during its retry window.

### ISSUE THREAD

**Issue by WinmezzZ** [anchan828/nest-redlock#703]
Hi, What is this problem? 

![CleanShot 2024-09-04 at 11 39 43@2x](https://github.com/user-attachments/assets/cfe2a7d2-fa0c-48c8-9c5d-3908d311bc0b)

**Comment by anchan828** [comment]
Hi @WinmezzZ, This package is a wrapper for [node-redlock](https://github.com/mike-marcacci/node-redlock), so it does not implement the algorithm of redlock itself.
Perhaps checking these Issues may provide the solution you are seeking.
https://github.com/mike-marcacci/node-redlock/issues/168
